app/__init__.py
app/extensions/__init__.py
app/modules/api/__init__.py
app/modules/api/v0/__init__.py
app/modules/api/v0/admin/models.py
app/modules/api/v0/admin/resources.py
app/modules/api/v0/schemas/__init__.py
app/modules/api/v0/users/models.py
app/settings/default.py
app/utils/__init__.py
app/utils/exceptions.py
app/utils/loading.py
app/utils/sessions.py

Implements basic some basic app functionality.
Of note are `loader` functions which are leveraged by `load` and `iter_loaders` in `app/utils/loading.py` to register endpoints to the application (though they could be used to do more than this).
To start the app:
```
from app import create_app
create_app().run(debug=True)
```
generated swagger docs at: http://127.0.0.1:5000/api/
More thorough description of the work herein pending...

app init via module collector

---

Untitled.ipynb
app/modules/api/v0/admin/models.py
app/modules/api/v0/admin/resources.py
app/utils/loading.py
test/utils/package/module.py
test/utils/package/subpackage/submodule.py
test/utils/package/subpackage/subsubpackage/__init__.py
test/utils/test_loading.py
testing.py

Fixes bug that prevented relative import from within loader modules.

fix relative import bug in loading

---

Untitled.ipynb
app/modules/api/v0/admin/models.py
app/modules/api/v0/admin/resources.py
app/utils/loading.py
test/utils/package/module.py
test/utils/package/subpackage/submodule.py
test/utils/package/subpackage/subsubpackage/__init__.py
test/utils/test_loading.py
testing.py

Reverts 3Blades/app-backend#19

Revert "Revert "fix relative import bug in loading""

---

.codeclimate.yml

Code climate with duplication, radon, fixme and pep8 engines.

Add code climate

---

.travis.yml

enable docker build

---

appdj/settings/base.py
appdj/urls.py

add static files serving for dev env

---

appdj/settings/base.py

static url fix

---

.travis.yml
appdj/urls.py

some fixes

---

actions/middleware.py

Fix action middleware when request has no user attr

---

actions/tests/test_middleware.py
appdj/settings/base.py
appdj/urls.py
base/pagination.py
base/swagger/codec.py
base/swagger/document.py
base/swagger/schema_generator.py
projects/models.py
projects/serializers.py
projects/views.py
servers/serializers.py
servers/views.py
users/views.py

Add ordering filter

---

users/management/commands/create_admin.py

Fix add admin command

---

users/__init__.py
users/apps.py
users/serializers.py
users/signals.py

Add signals for user profile and token creation

---

actions/tests/test_middleware.py
actions/tests/test_views.py
projects/tests/test_views.py
servers/tests/test_spawners.py
servers/tests/test_views.py
users/tests/factories.py

Fix tests after signals

---

users/management/commands/create_admin.py

Add profile and token creation for admin user

---

appdj/settings/base.py
requirements/base.txt

PR to Merge changes for Issue #80 , handling CORS requests.

fix/iss80 Add Django CORS Headers to handle CORS requests.

---

appdj/settings/base.py

Fix 3Blades/app-backend#97

---

projects/serializers.py
projects/tests/test_views.py

Closes 3Blades/app-backend#96

---

projects/serializers.py

Add collaborators to project serializer 3Blades/cli-tools#76

---

users/signals.py
users/tests/factories.py

Remove user token creation signal

---

appdj/settings/base.py
projects/serializers.py
projects/views.py

Add user details to collaborator; fix project files listing

---

servers/spawners.py
servers/tests/test_spawners.py
utils.py

Fix for 3Blades/app-backend#116

Fix server spawning auth

---

projects/serializers.py
projects/tests/test_views.py

Fix project creation for staff user 3Blades/app-backend#117

---

servers/admin.py

Add environment resource admin pages 3Blades/react-frontend#83

---

base/permissions.py
users/tests/test_views.py
users/views.py

Fix user deletion 3Blades/cli-tools#79

---

actions/middleware.py
actions/tests/test_middleware.py
appdj/settings/base.py
billing/middleware.py

Fix login error

---

projects/serializers.py

More clear error during adding user to project

---

projects/file_watch_handler.py
projects/models.py
projects/tests/test_file_watcher.py
projects/tests/test_views.py
projects/tests/utils.py
run_watchman.py
watchman_trigger.sh

feature/issue #146 Add script to create Watchman trigger and python code to handle alerts sent by the trigger. Small changes to unit tests.

feature/issue #146 - Add File Watcher

---

.travis.yml
config/buildDockerImage.sh

Signed-off-by: Greg Werner <werner.greg@gmail.com>
Closes #169 #170

no travis build w/ pr's

---

projects/views.py

fix/issue #176 - Small bugfix for the case of using both name and path fields combined with base64_data.

Fix Nested Uploads for Base64 Data

---

.travis.yml

Add test command to travis

---

projects/serializers.py
projects/tests/test_views.py

3Blades/app-backend#181
It can't be done easily on db level. I just added validation on project name field.

Fixes 3Blades/app-backend#181

---

appdj/urls.py
users/tests/factories.py
users/tests/test_views.py
users/views.py

feature/issue #188 - Allow users to view all of their own emails, as well as other users public emails.

feature/issue #188 - Create get method to obtain public user profile emails

---

appdj/urls/base.py
appdj/urls/unversioned.py

fix/issue #199 - Refactor the URLs.

Refactor the URLconfs to remove necessary URLs from versioning scheme.

---

search/tests/test_views.py
search/views.py

Fix search

---

watchman_trigger.sh

Your branch is up-to-date with 'origin/master'.
Changes to be committed:
modified:   watchman
modified:   watchman_trigger.sh

 On branch master

---

users/serializers.py
users/tests/test_views.py
users/views.py

fix/issue #214 - Make sure integration aware of the correct user, fix validation for extra_data field.

Fix/issue #214 Integrations endpoint doesn't exist for users

---

servers/permissions.py

Fixes  3Blades/app-backend#224

Fix server stats

---

billing/models.py
billing/tests/mock_stripe.py
billing/views.py

fix/issue #228 - Cannot access customer data when creating a new customer.

Fix CustomerViewSet

---

users/serializers.py

Add the missing id field to the Integration serializer.

---

projects/serializers.py
projects/tests/test_views.py

fix/issue #210 - Not able to add project collaborator.

Fix Collaborator Validation

---

README.md
docker-entrypoint.sh
watchman_trigger.sh

On 16.04 we need to force a service reload before a restart.

Service reload on before a restart on 16.04 

---

infrastructure/models.py

Fix hosts endpoint

---

actions/middleware.py
actions/tests/test_middleware.py
triggers/serializers.py

Related to 3Blades/app-backend#246

Fix actions and triggers middleware

---

Dockerfile
requirements/base.txt

Additional Libraries
add jpeg-dev
add libjpeg
https://pillow.readthedocs.io/en/latest/installation.html

Pull Request for Pillow requirements

---

servers/models.py
servers/serializers.py
servers/tests/test_views.py

fix/issue #252 - Validate Server Type During Creation

Make sure that config['type'] is valid.

---

actions/tests/test_views.py
projects/models.py
servers/models.py

Further fixes for action list view

---

.travis.yml

Drop python 3.5

---

search/tests/test_views.py

Remove unnecessary test

---

appdj/settings/base.py

Fix jupyter notebook startup 3Blades/3blades#114

---

actions/middleware.py
appdj/settings/base.py
appdj/urls/base.py
requirements/base.txt

feature/issue #266 - Backed Support for Password Reset.

Add djoser package for password reset functionality

---

users/models.py

fix/issue #277 - Implement Custom User Manager: This fixes the issue.

Add CustomUserManager

---

appdj/settings/prod.py

Remove unnecessary things from production settings

---

projects/views.py

fix/issue #283 - Project PATCH Fails

Fix Project viewset to handle PATCH properly.

---

appdj/urls/base.py
base/tests/test_views.py
base/views.py

<feature><chore>/issue #285 - Add status endpoint for StatusCake.

Add tbs-status endpoint and unit test.

---

config/buildDockerImage.sh

Previous command just listed the jobs. Did that to make sure I was not going to break anything.
This one will actually run the dev-deploy on master merge.

Updated to actually Run the job

---

docker-entrypoint.sh

Update the create_resource command to create_server_size.

---

servers/models.py
servers/tests/test_models.py

[fix]/issue #295 - Issue starting Resource { server } Prod-blue-green as a new user.

Slugify server container 

---

requirements/base.txt

Upgrade celery

---

config/buildDockerImage.sh

Misread the API call to rundeck.

Manually tested API call

---

config/buildDockerImage.sh

Fix shell script.

---

appdj/urls/unversioned.py
base/permissions.py
billing/views.py
servers/models.py
servers/tests/test_views.py
servers/views.py

[fix] - issue #304 - Remove namespace from ServerSize URLs.

Fix ServerSize URLs

---

users/management/commands/create_admin.py
users/models.py
users/tests/test_backends.py
users/tests/test_create_admin.py
users/tests/test_models.py

[fix] - issue #310 - Ensure users are unique.

Fix user save

---

triggers/serializers.py
triggers/views.py

Server trigger fixes

---

users/models.py
users/tests/test_views.py

[chore] - issue #317 - Change Avatar Storage Location.

Change the upload_to of avatars, adjust unit test.

---

billing/serializers.py

[fix]/issue #321 - Eliminate token requirement.

Dont req card token

---

projects/serializers.py
projects/views.py

[fix]/issue #334 Remove File Field from ProjectFile Responses.

Make the file field write only for now.

---

base/permissions.py
users/tests/test_views.py
users/views.py

Make POST users/profiles/ only available to admin users.

---

triggers/views.py

[fix]/issue #338 - API Testing Errors. 

Fix the lookup for server triggers.

---

servers/tasks.py
triggers/serializers.py
users/models.py
users/tests/test_views.py
users/views.py

[fix]/issue #338 - API Testing errors

Add an update method for trigger serializer, dont delete servers on terminate

---

base/namespace.py
projects/tests/test_views.py
users/models.py

[fix]/issue #346 Fix Namespace Query

Add filter to Namespace lookup, unit tests.

---

appdj/settings/base.py

[fix]/issue #348 - Cannot start a server.

Add port 8888 to server port mapping.

---

billing/signals.py
billing/stripe_utils.py
billing/tests/mock_stripe.py
billing/tests/test_middleware.py
billing/tests/test_signals.py
billing/tests/test_stripe_utils.py
billing/tests/test_views.py

Default Subscriptions for Users

---

.travis.yml
config/buildDockerImage.sh

#361 
Signed: mroach@3blades.io

CHORE: Update build process

---

users/views.py

Make the avatar endpoint csrf exempt.

---

infrastructure/models.py
infrastructure/tests/test_models.py
requirements/base.txt
servers/spawners.py
servers/tests/fake_docker_api_client/fake_api_client.py
servers/tests/test_spawners.py

Issue #364 - Upgrade Python Docker SDK

Upgrade Docker SDK, make necessary code changes to support new version.

---

billing/tests/test_stripe_utils.py

Add a unit test to verify inactive servers are found

---

appdj/settings/base.py
appdj/urls/unversioned.py
servers/spawners.py
servers/tests/test_spawners.py

Handle container creation on non GPU enabled instances.

---

servers/spawners.py

Terminate Currently Running Containers Properly

---

projects/managers.py
projects/tests/test_views.py

Fix tbs_get for collaborators, add unit tests

---

servers/serializers.py
servers/tests/test_views.py

Add access_token to server payload

---

appdj/urls/unversioned.py
users/tests/test_views.py
users/views.py

Add the Me Endpoint

---

billing/tests/mock_stripe/__init__.py
billing/tests/mock_stripe/error.py
billing/tests/test_views.py
billing/views.py

Catch Stripe Errors when Creating Card

---

billing/stripe_utils.py

Do not attempt to create free plan in DB if it already exists.

---

billing/stripe_utils.py

Add created to avoid null constraint violation.

---

appdj/settings/base.py
billing/stripe_utils.py

Update the use SSL setting.

---

docker-compose.yml

Add nginx to docker compose

---

users/tests/test_views.py
users/views.py

Ensure that full avatar URL is returned when posting to avatar endpoint.

---

billing/stripe_utils.py
billing/tests/mock_stripe/__init__.py
billing/tests/test_views.py
notifications/tests/test_signals.py

Fix non-deterministic tests

---

billing/stripe_utils.py
billing/tests/test_stripe_utils.py
projects/file_watch_handler.py
projects/tests/test_file_watcher.py

Fix a few bugs found by Sentry.

---

users/serializers.py
users/views.py

Change the to_representation method to always include full URL

---

projects/models.py
projects/storage.py
projects/tests/test_utils.py
projects/tests/test_views.py
projects/tests/utils.py
projects/utils.py
projects/views.py

Create synchronization method and supporting architecture 

---

projects/views.py

Re-add import.

---

projects/storage.py
projects/tests/test_utils.py
projects/tests/test_views.py

Correct the name the file is created in the database with

---

actions/middleware.py
appdj/settings/base.py
jwt_auth/middleware.py
jwt_auth/serializers.py
jwt_auth/tests/test_middleware.py
jwt_auth/tests/test_utils.py
jwt_auth/utils.py
jwt_auth/views.py

OAuth frontend redirect

---

appdj/settings/base.py
appdj/urls/base.py
jwt_auth/tests/test_utils.py
users/tests/test_views.py
users/views.py

Fixes for frontend OAuth

---

users/serializers.py
users/tests/test_views.py

Add serializer validations for email uniqueness

---

notifications/templates/notifications/base_email_template.html
notifications/templates/notifications/base_email_template.txt
notifications/templates/notifications/payment_failed.html
notifications/templates/notifications/payment_failed.txt
notifications/templates/notifications/payment_successful.html
notifications/templates/notifications/payment_successful.txt
notifications/templates/notifications/subscription_canceled.html
notifications/templates/notifications/subscription_canceled.txt
notifications/templates/notifications/subscription_created.html
notifications/templates/notifications/subscription_created.txt
notifications/templates/notifications/trial_ended.html
notifications/templates/notifications/trial_ended.txt
notifications/templates/notifications/trial_will_end.html
notifications/templates/notifications/trial_will_end.txt
notifications/templatetags/divide.py
notifications/templatetags/usd.py
notifications/tests/test_signals.py
notifications/tests/test_templatetags.py
notifications/utils.py

Define notification email templates

---

users/serializers.py
users/tests/test_views.py

Only serialize avatar if the user has one

---

projects/tests/test_views.py
projects/views.py

Filter out projects that are private and I am not a collaborator on.

---

notifications/utils.py
users/tests/test_views.py
users/views.py

Only attempt to update user email if it's different. 

---

users/serializers.py
users/tests/test_views.py

Force avatars to be served over HTTPS.

---

users/tests/test_views.py
users/views.py
utils.py

Allow non-admin users to delete their own accounts

---

billing/stripe_utils.py
billing/tests/test_views.py
billing/views.py

Only send payment failure notifications when subscription was active

---

projects/file_watch_handler.py

Skip .ssh directory

---

projects/file_watch_handler.py

Log and Continue if the User Cannot be Found

---

servers/spawners.py

It should work, testing is tricky here, because we'd need additional http server in parallel with test runner. This is possible, but I can't make it work for some reason.

fix: issue #477 - Cant' Start Notebook nor Rstudio in Dev

---

servers/spawners.py

Fix stupidity

---

servers/spawners.py
servers/tests/test_spawners.py

Disable gpu for rstudio

---

servers/spawners.py

Change ordering of if statement to use short circuiting

---

projects/tests/test_views.py
servers/spawners.py

Pass empty dict to volume config when it's not being used.

---

servers/spawners.py

Don't add volume config for RStudio images

---

billing/stripe_utils.py
billing/tests/test_views.py
billing/views.py
teams/tests/test_views.py
users/tests/test_views.py
users/views.py

Cancel subscription upon deletion of user account

---

billing/stripe_utils.py
billing/tests/test_views.py
billing/views.py
teams/tests/test_views.py
users/tests/test_views.py

Fix broken unit tests.

---

jwt_auth/views.py

Remove trial about to expire notification from app-backend.

---

projects/file_watch_handler.py
projects/utils.py

Ignore nfs files

---

projects/urls.py

Fix the project URLs conf again

---

users/tests/test_views.py
users/views.py

Pass request as part of context for user serializer

---

appdj/settings/dev.py

Add sentry config to dev settings.

---

projects/views.py

Fix get_queryset to return correct projects

---

projects/tests/test_views.py
projects/views.py

Fix get_queryset and get_object to correctly account for query params

---

projects/views.py

Fix project update and deletion.

---

projects/models.py
projects/utils.py

Allow hyphens and underscores in project names

---

billing/tests/factories.py
billing/tests/test_stripe_utils.py
billing/tests/test_views.py
billing/tests/utilities.py

Make plan creation and cleanup more fail safe for tests.

---

search/tests/test_views.py
search/views.py

Filter out the bad results before returning

---

servers/spawners/ecs.py
servers/tests/test_spawners.py

Fix ecs routing

---

servers/spawners/ecs.py
servers/tests/test_spawners.py

Fix ecs status error
